MH-203: Refactoring the basic donations page, needs conditional rendering
ModularHistory/modularhistory pull request #382
Opened 2021-05-09 18:43 UTC by sunzae99

Made changes to the styling of the pages, but still need conditional rendering fixed. I have tried the code and is commented out. I was not entirely sure why the code was not working. I will really appreciate anyone's input.

2021-05-10 21:23 UTC, iacobfred commented on frontend/pages/donations/make.tsx
>    const [clientToken, setClientToken] = useState(props.clientToken);
@sunzae99, maybe we should use state for `success` and `error`, to help with conditional rendering.

We could do it like this:
```
const [success, setSuccess] = useState(false); 
const [error, setError] = useState(false); 
```

2021-05-10 21:25 UTC, iacobfred commented on frontend/pages/donations/make.tsx
> +          // return <SuccessMessage />;
@sunzae99, if we use state (suggested in https://github.com/ModularHistory/modularhistory/pull/382/files#r629693380), we could do this:
```
if (response.data == "OK") {
    setSuccess(true);
} else {
    setError(true);
}
```

2021-09-09 03:05 UTC, mattfredericksen requested changes
Before we can allow users to navigate to this page in production, we'll need some more input validation (e.g. don't allow API requests with no amount entered, or a negative amount entered), but we probably don't need that on this PR.

2021-09-09 06:28 UTC, mattfredericksen commented on frontend/pages/donations/make.tsx
>  const Donate: FC<DonateProps> = (props: DonateProps) => {
That is not completely true actually. We really just want to clearly indication which component is the core page component, so I would suggest naming this component `MakeDonationPage` or something similar with `Page` on the end.

2021-09-09 15:44 UTC, mattfredericksen approved these changes
LGTM!

2021-09-09 15:58 UTC, iacobfred approved these changes
LGTM! We'll want to make some changes to the text of the error message and success message, but we can do that in a future PR.

2021-09-10 01:02 UTC, sunzae99 commented
> LGTM! We'll want to make some changes to the text of the error message and success message, but we can do that in a future PR.

What changes would you like to see? @iacobfred @mattfredericksen. I am free to work with your guys' suggestions :)

2021-09-10 04:19 UTC, iacobfred commented
> > LGTM! We'll want to make some changes to the text of the error message and success message, but we can do that in a future PR.
> 
> What changes would you like to see? @iacobfred @mattfredericksen. I am free to work with your guys' suggestions :)

I'd like to think more about the textual content of the donations page, but we don't need to worry about that right now. Good work @sunzae99. Let's merge it. : - )

2021-09-10 04:23 UTC, merged