MH-87: add collections page
ModularHistory/modularhistory pull request #837
Opened 2021-10-27 00:16 UTC by nickghuman

Created collections page

2021-11-01 21:46 UTC, iacobfred commented on frontend/pages/collections/index.page.tsx
> +        title={"Occurrences"}
@nickghuman, can you update this to `"Collections"`?

2021-11-01 21:49 UTC, iacobfred requested changes

2021-11-01 21:49 UTC, iacobfred commented on frontend/pages/collections/index.page.tsx
> +          "Browse historical occurrences related to your topics or entities of interest."
How about `"Browse collections of historical occurrences, entities, sources, and more related to your topics of interest."` ?

2021-11-01 21:49 UTC, iacobfred commented on frontend/pages/collections/[slug].page.tsx
> + * A page that renders the HTML of a single entity.
--> 
```
* The collections page:
* http://www.modularhistory.com/collections
```

2021-11-03 14:33 UTC, iacobfred approved these changes

2021-11-03 15:48 UTC, mattfredericksen approved these changes
LGM

2021-11-03 15:52 UTC, merged