MH-250: Added Featured Content to ModularHistory Homepage
ModularHistory/modularhistory pull request #845
Opened 2021-10-29 00:18 UTC by sunzae99

The Featured Content is currently being implemented using the ModuleUnionCard, which needs some styling. (This can be done later, in a separate ticket)

2021-10-31 00:43 UTC, sunzae99 commented on frontend/pages/index.page.tsx
> +const FeatureContent: FC = () => {
Made changes on the following commit!

2021-10-31 00:44 UTC, sunzae99 commented on frontend/pages/index.page.tsx
> +                    <p>There are no modules associated with this date.</p>
![screencapture-modularhistory-dev-net-2021-10-30-19_44_08](https://user-images.githubusercontent.com/70658409/139562209-b31d7e88-f879-4971-bc3e-9733641da5b8.png)

2021-11-01 15:39 UTC, iacobfred requested changes

2021-11-01 15:39 UTC, iacobfred commented on apps/home/api/urls.py
> +    path('feature/', views.FeatureAPIView.as_view()),
_nit_: Let's make this plural: `'features/'`

2021-11-01 15:39 UTC, iacobfred commented on frontend/pages/index.page.tsx
> +        <Grid item xs={12} sm={6} md={6}>
@sunzae99, the featured content should be displayed before the "today in history" content, I think.

2021-11-01 15:39 UTC, iacobfred commented on frontend/pages/index.page.tsx
> +                      <Skeleton sx={{ minHeight: 200 }} />
nit: Let's make this `Skeleton` full-width.

2021-11-01 21:51 UTC, iacobfred approved these changes

2021-11-01 23:43 UTC, merged