Mh 91
ModularHistory/modularhistory pull request #884
Opened 2021-11-15 20:56 UTC by aaw0151

2021-11-15 20:57 UTC, aaw0151 commented
Before update:
![image](https://user-images.githubusercontent.com/59071999/141852717-9276b8d4-aa64-4e8e-a949-4807ba4c2bc1.png)

After update:
![image](https://user-images.githubusercontent.com/59071999/141852844-da65ce2e-31cd-42df-bdda-6a3d3a1f647b.png)

2021-11-15 21:04 UTC, aaw0151 commented
I only changed one file `/modularhistory/frontend/components/cards/ModuleCard.tsx`. I'm not sure why my files from https://github.com/ModularHistory/modularhistory/pull/862 are being committed as well.

@mattfredericksen @iacobfred do you know why that would be?

2021-11-16 21:45 UTC, mattfredericksen commented
> I only changed one file `/modularhistory/frontend/components/cards/ModuleCard.tsx`. I'm not sure why my files from #862 are being committed as well.

I think that just means at you branched from `MH-268` instead of `main` when creating this branch. I'll see if I can correct it.

2021-11-16 21:54 UTC, aaw0151 commented
> > I only changed one file `/modularhistory/frontend/components/cards/ModuleCard.tsx`. I'm not sure why my files from #862 are being committed as well.
> 
> I think that just means at you branched from `MH-268` instead of `main` when creating this branch. I'll see if I can correct it.

Ah I probably did do that, my bad.

2021-11-16 22:16 UTC, mattfredericksen commented on frontend/components/cards/ModuleCard.tsx
> +    //bgImage.title = module.title;
If this line is unneeded it should be removed.

2021-11-16 22:16 UTC, mattfredericksen reviewed
@iacobfred leaving review to you since this affects site content.

2021-11-16 22:16 UTC, mattfredericksen commented on frontend/components/cards/ModuleCard.tsx
> +    //bgImage.title = module.title;
If this line is unneeded it should be removed.

2021-11-19 05:38 UTC, iacobfred reviewed
Hmmm, it looks like this PR currently does not add an alt attribute to images. It is adding an `aria-label` attribute to the cards that have image backgrounds, which I don't think is necessary, since screen readers are able to read the textual content of these cards. We probably don't want screen readers to read the caption of the background image for each result on the SERP; we just want the screen readers to read the card titles and truncated module descriptions.

We specifically want `alt` attributes on `img` elements because pages can be penalized by Google if they are missing `alt` text for images. Elements with image backgrounds are fine, though, because the background is just there for style and doesn't necessarily need to be communicated to blind people.

Another thing to consider: since we use `figcaption` elements to display captions underneath our images (including images that are rendered with `img` tags rather than as div backgrounds), and since screen readers will read both the `alt` and `figcaption` content, we should differentiate the two. I just read this article about the difference in usage of `alt` and `figcaption`: https://thoughtbot.com/blog/alt-vs-figcaption

Basically, for an `img` element that depicts an image of Mark Twain sitting in a chair in 1875, the `alt` text would be something like "A man sitting in a chair" and the ficaption text would be something like "Mark Twain, 1875."

So, in order to complete MH-91, I think we should do the following:
- Add an `alt_text` field to the Image model
- Search for all instances of `<img` in our code base (note: currently, we only render img tags in Django templates, not directly on React pages, but the Django templates are used to generate some of the HTML content that is sent to the frontend by our API... so TL;DR: we'll just need to update the img tags that appear in our Django templates)
- Anywhere we render an img tag, we'll need to add an `alt` attribute that uses the `alt_text` field if there's a value—something like `<img alt="{% if image.alt_text %}{{ image.alt_text }}{% endif %}" ... />` (which will render `alt=""` if there's no alt text value).

2021-11-19 20:58 UTC, iacobfred requested changes
See https://github.com/ModularHistory/modularhistory/pull/884#pullrequestreview-810777224

2021-12-02 17:26 UTC, closed without merging