MH-269: Added related entities to entity pages.
ModularHistory/modularhistory pull request #886
Opened 2021-11-18 05:36 UTC by aaw0151

2021-11-18 05:37 UTC, aaw0151 commented
Currently a work in progress. Frontend styling has not been completed.

2021-11-19 05:44 UTC, iacobfred requested changes

2021-11-19 05:44 UTC, iacobfred commented on frontend/pages/entities/[slug].page.tsx
> +        {entity.relatedEntities?.map((relatedEntity) => (
There probably should be a "Related entities" header/label above wherever the related entities are displayed (but only if `!!entity.relatedEntities?.length`).

2021-11-19 20:08 UTC, aaw0151 commented
![image](https://user-images.githubusercontent.com/59071999/142685290-469283e1-5c4d-4804-b046-0cfcac0c130f.png)

Current implementation layout.

2021-11-21 04:37 UTC, mattfredericksen requested changes

2021-11-21 04:37 UTC, mattfredericksen commented on frontend/pages/entities/[slug].page.tsx
> +
Let's extract all the styles that are shared between this and `EntityRelatedQuoteCard` to a `sharedStyles` object.
E.g.
```ts
const sharedStyles: CSSProperties = {
  cursor: "pointer",
}

const EntityRelatedQuoteCard = styled(Card)({
  ...sharedStyles,
  otherStyles
})

const EntityRelatedEntityCard = styled(Card)({
  ...sharedStyles,
  otherStyles
})
```

2021-11-21 04:37 UTC, mattfredericksen commented on frontend/pages/entities/[slug].page.tsx
> +                </Link>
We don't need `passHref` here.
https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

2021-12-19 22:10 UTC, closed without merging